import os
import sys
import subprocess
import tempfile
import streamlit as st
from pathlib import Path
from data_ingestion import ingest_report_package

def get_base_path():
    return Path(__file__).parent.resolve()

# Auto-install Node.js dependencies dynamically (bypassing apt-get)
def setup_node_environment():
    base_path = get_base_path()
    node_env_dir = base_path / "node_env"
    
    # 1. Install Node.js locally via Python if missing
    if not node_env_dir.exists():
        with st.spinner("Downloading Node.js (bypassing apt-get)..."):
            subprocess.run([sys.executable, "-m", "nodeenv", str(node_env_dir)], check=True)
            
    # 2. Add Node to system PATH (handling both Windows and Linux paths)
    node_bin = str(node_env_dir / "bin")
    node_scripts = str(node_env_dir / "Scripts")
    
    if node_bin not in os.environ["PATH"]:
        os.environ["PATH"] = f"{node_bin}{os.pathsep}{os.environ['PATH']}"
    if node_scripts not in os.environ["PATH"]:
        os.environ["PATH"] = f"{node_scripts}{os.pathsep}{os.environ['PATH']}"
        
    # 3. Install NPM packages
    if not (base_path / "node_modules").exists():
        with st.spinner("Installing NPM dependencies..."):
            import shutil
            npm_exec = shutil.which("npm")
            if not npm_exec:
                st.error("❌ Cannot find 'npm' executable after nodeenv setup!")
                st.stop()
                
            try:
                subprocess.run(
                    [npm_exec, "install"], 
                    cwd=str(base_path), 
                    check=True, 
                    capture_output=True, 
                    text=True
                )
            except subprocess.CalledProcessError as e:
                st.error("❌ NPM Install Failed!")
                st.code(f"STDOUT:\n{e.stdout}\n\nSTDERR:\n{e.stderr}")
                st.stop()

setup_node_environment()


def generate_pdf(report_data, output_pdf_path):
    temp_dir = report_data.get('__temp_dir')
    json_file_name = report_data.get('__json_file_name')
    
    if not temp_dir or not json_file_name:
        raise ValueError("Missing temporary directory or JSON file name from ingestion pipeline.")

    base_path = get_base_path()
    generate_js_path = base_path / "scripts" / "generate.js"
    
    import shutil
    node_exec = shutil.which("node")
    if not node_exec:
        raise RuntimeError("Cannot find 'node' executable in PATH.")

    result = subprocess.run(
        [node_exec, str(generate_js_path), str(temp_dir), str(json_file_name), str(output_pdf_path)],
        cwd=str(base_path),
        capture_output=True,
        text=True,
        encoding="utf-8"
    )
    
    if result.returncode != 0:
        st.error("Node.js generator failed!")
        st.text(result.stdout)
        st.text(result.stderr)
        raise RuntimeError("PDF Generation failed via Node.js")
    
    return output_pdf_path

st.set_page_config(page_title="Asset Tracker PDF Generator", layout="centered")

hide_github_icon = """
<style>
.css-1jc7ptx, .e1ewe7hr3, .viewerBadge_container__1QSob, .styles_viewerBadge__1yB5_, .viewerBadge_link__1S137, .viewerBadge_text__1JaDK{ display: none; } #MainMenu{ visibility: hidden; } footer { visibility: hidden; } header { visibility: hidden; }
</style>
"""
st.markdown(hide_github_icon, unsafe_allow_html=True)

st.title("📄 CML PDF Generator")
st.write("Upload a CML Report ZIP file to automatically generate your PDF report.")

uploaded_file = st.file_uploader("Upload Report ZIP", type="zip")

if uploaded_file is not None:
    st.info(f"Processing {uploaded_file.name}...")
    
    with tempfile.TemporaryDirectory() as work_dir:
        zip_path = Path(work_dir) / uploaded_file.name
        pdf_path = Path(work_dir) / f"{Path(uploaded_file.name).stem}_Report.pdf"
        
        with open(zip_path, "wb") as f:
            f.write(uploaded_file.getbuffer())
            
        try:
            with st.spinner("Extracting and processing data..."):
                with ingest_report_package(zip_path) as report_data:
                    generate_pdf(report_data, pdf_path)
            
            # Check what files were actually generated by the JS script
            vessel_pdf_path = Path(work_dir) / f"{pdf_path.stem}_Vessel.pdf"
            piping_pdf_path = Path(work_dir) / f"{pdf_path.stem}_Piping.pdf"
            
            if vessel_pdf_path.exists() or piping_pdf_path.exists():
                st.success("✅ PDFs Generated Successfully!")
                
                col1, col2 = st.columns(2)
                
                if vessel_pdf_path.exists():
                    with open(vessel_pdf_path, "rb") as f:
                        col1.download_button(
                            label="⬇️ Download Vessel Report",
                            data=f.read(),
                            file_name=vessel_pdf_path.name,
                            mime="application/pdf",
                            use_container_width=True
                        )
                        
                if piping_pdf_path.exists():
                    with open(piping_pdf_path, "rb") as f:
                        col2.download_button(
                            label="⬇️ Download Piping Report",
                            data=f.read(),
                            file_name=piping_pdf_path.name,
                            mime="application/pdf",
                            use_container_width=True
                        )
            else:
                # Fallback if only the single/empty report generated
                fallback_path = Path(work_dir) / f"{pdf_path.stem}_Empty.pdf"
                if not fallback_path.exists():
                    fallback_path = pdf_path
                
                if fallback_path.exists():
                    st.success("✅ PDF Generated Successfully!")
                    with open(fallback_path, "rb") as f:
                        st.download_button(
                            label="⬇️ Download PDF Report",
                            data=f.read(),
                            file_name=fallback_path.name,
                            mime="application/pdf",
                            use_container_width=True
                        )
            
        except Exception as e:
            st.error(f"An error occurred: {e}")
